### ISSUE TITLE
issue with makefile

### ISSUE THREAD

**Issue by benkeser** [JustinJNaidu/Sleep_Health#2]
You have an issue with your make command. Please see hints on canvas again. I will regrade when this issue is closed.

**Comment by JustinJNaidu** [comment]
Hi Dr. Benkeser. I have modified the make command rule in the Makefile.

These were some changes I made based on your hints via Canvas:

For Windows Users
docker-run:
	`docker run -v "/$$(pwd)"/report:/project/report justinnaidu/sleep_project`

For Mac Users
docker-run-m:
	`docker run -v "$$(pwd)"/report:/project/report justinnaidu/sleep_project`
	
Please let me know if it works on your end. 

Best,
Justin
